<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="Vishals-Mac.local" name="com.mobile.tests.GDPR_MetaAppE2ETests" tests="21" failures="7" timestamp="18 May 2020 12:03:38 GMT" time="1003.934" errors="4">
  <testcase name="CheckNoMessageWithShowOnceCriteriaWhenConsentAlreadySaved" time="60.779" classname="com.mobile.tests.GDPR_MetaAppE2ETests"/>
  <testcase name="CheckSavedConsentAlwaysWithSameAuthID" time="49.061" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.cybage.frameworkutility.assertion.CustomSoftAssert.assertAll(CustomSoftAssert.java:310)
	at com.mobile.tests.GDPR_MetaAppE2ETests.CheckSavedConsentAlwaysWithSameAuthID(GDPR_MetaAppE2ETests.java:1497)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- CheckSavedConsentAlwaysWithSameAuthID -->
  <testcase name="CreateAndLauncheNewSiteWithAppLaunchParameter_CheckConsent" time="15.400" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <skipped/>
  </testcase> <!-- CreateAndLauncheNewSiteWithAppLaunchParameter_CheckConsent -->
  <testcase name="CheckConsentForTargetingParameterAfterRejectAll" time="47.863" classname="com.mobile.tests.GDPR_MetaAppE2ETests"/>
  <testcase name="CheckErrorForDuplicateSite" time="33.672" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 8, Size: 8">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.mobile.tests.GDPR_MetaAppE2ETests.CheckErrorForDuplicateSite(GDPR_MetaAppE2ETests.java:1196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- CheckErrorForDuplicateSite -->
  <testcase name="CheckErrorForWrongSiteIdWhileCreatingNewSite" time="33.464" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Internal Server Error] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Internal Server Error] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.cybage.frameworkutility.assertion.CustomSoftAssert.assertAll(CustomSoftAssert.java:310)
	at com.mobile.tests.GDPR_MetaAppE2ETests.CheckErrorForWrongSiteIdWhileCreatingNewSite(GDPR_MetaAppE2ETests.java:1276)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- CheckErrorForWrongSiteIdWhileCreatingNewSite -->
  <testcase name="CheckConsentMessageDisplayAfterDeleteCookies" time="40.510" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <failure type="java.lang.AssertionError" message="Exception occured while clicking on Located by By.chained({By.xpath: //android.widget.Button[@content-desc=&#039;Accept All cookies&#039;]})Exception details - Can&#039;t locate an element by this strategy: By.chained({By.xpath: //android.widget.Button[@content-desc=&#039;Accept All cookies&#039;]})">
      <![CDATA[java.lang.AssertionError: Exception occured while clicking on Located by By.chained({By.xpath: //android.widget.Button[@content-desc='Accept All cookies']})Exception details - Can't locate an element by this strategy: By.chained({By.xpath: //android.widget.Button[@content-desc='Accept All cookies']})
	at org.testng.Assert.fail(Assert.java:93)
	at com.cybage.frameworkutility.utilities.Report.LogFailwithScreenCapture(Report.java:903)
	at com.cybage.mobileFramework.BaseMobileDriver.clickOn(BaseMobileDriver.java:340)
	at com.mobile.tests.GDPR_MetaAppE2ETests.CheckConsentMessageDisplayAfterDeleteCookies(GDPR_MetaAppE2ETests.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- CheckConsentMessageDisplayAfterDeleteCookies -->
  <testcase name="CheckErrorForMandatoryFieldForCreateNewSite" time="67.570" classname="com.mobile.tests.GDPR_MetaAppE2ETests"/>
  <testcase name="CheckConsentWithSameAuthIDAfterDeletingAndRecreate" time="125.018" classname="com.mobile.tests.GDPR_MetaAppE2ETests"/>
  <testcase name="EditSiteWithConsentGivenBefore" time="82.363" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <skipped/>
  </testcase> <!-- EditSiteWithConsentGivenBefore -->
  <testcase name="CheckConsentForTargetingParameterAfterAcceptAll" time="57.731" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 5, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 5, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.mobile.tests.GDPR_MetaAppE2ETests.CheckConsentForTargetingParameterAfterAcceptAll(GDPR_MetaAppE2ETests.java:432)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- CheckConsentForTargetingParameterAfterAcceptAll -->
  <testcase name="CheckConsentWithSameAuthIDWithNewInstallation" time="51.965" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <failure type="java.lang.AssertionError" message="Exception occured while clicking on Located by By.chained({By.xpath: //android.view.View[@text=&#039;Accept All&#039;]})Exception details - Can&#039;t locate an element by this strategy: By.chained({By.xpath: //android.view.View[@text=&#039;Accept All&#039;]})">
      <![CDATA[java.lang.AssertionError: Exception occured while clicking on Located by By.chained({By.xpath: //android.view.View[@text='Accept All']})Exception details - Can't locate an element by this strategy: By.chained({By.xpath: //android.view.View[@text='Accept All']})
	at org.testng.Assert.fail(Assert.java:93)
	at com.cybage.frameworkutility.utilities.Report.LogFailwithScreenCapture(Report.java:903)
	at com.cybage.mobileFramework.BaseMobileDriver.clickOn(BaseMobileDriver.java:340)
	at com.mobile.tests.GDPR_MetaAppE2ETests.CheckConsentWithSameAuthIDWithNewInstallation(GDPR_MetaAppE2ETests.java:1569)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- CheckConsentWithSameAuthIDWithNewInstallation -->
  <testcase name="CheckNoConsentMessageDisplayAfterShowSiteInfo" time="39.922" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <failure type="java.lang.AssertionError" message="Exception occured while clicking on Located by By.chained({By.xpath: //android.widget.Button[@content-desc=&#039;Accept All cookies&#039;]})Exception details - Can&#039;t locate an element by this strategy: By.chained({By.xpath: //android.widget.Button[@content-desc=&#039;Accept All cookies&#039;]})">
      <![CDATA[java.lang.AssertionError: Exception occured while clicking on Located by By.chained({By.xpath: //android.widget.Button[@content-desc='Accept All cookies']})Exception details - Can't locate an element by this strategy: By.chained({By.xpath: //android.widget.Button[@content-desc='Accept All cookies']})
	at org.testng.Assert.fail(Assert.java:93)
	at com.cybage.frameworkutility.utilities.Report.LogFailwithScreenCapture(Report.java:903)
	at com.cybage.mobileFramework.BaseMobileDriver.clickOn(BaseMobileDriver.java:340)
	at com.mobile.tests.GDPR_MetaAppE2ETests.CheckNoConsentMessageDisplayAfterShowSiteInfo(GDPR_MetaAppE2ETests.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- CheckNoConsentMessageDisplayAfterShowSiteInfo -->
  <testcase name="CheckSavedConsentAlwaysWithSameAuthIDCrossPlatform" time="134.728" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <error type="org.openqa.selenium.WebDriverException" message="unknown error: unable to discover open pages
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.14.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 71.73 seconds
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;Vishals-Mac.local&#039;, ip: &#039;fe80:0:0:0:c20:3d65:1640:1787%en0&#039;, os.name: &#039;Mac OS X&#039;, os.arch: &#039;x86_64&#039;, os.version: &#039;10.14.6&#039;, java.version: &#039;1.8.0_222&#039;
Driver info: driver.version: ChromeDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.14.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 71.73 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Vishals-Mac.local', ip: 'fe80:0:0:0:c20:3d65:1640:1787%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_222'
Driver info: driver.version: ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at com.mobile.tests.GDPR_MetaAppE2ETests.CheckSavedConsentAlwaysWithSameAuthIDCrossPlatform(GDPR_MetaAppE2ETests.java:1705)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- CheckSavedConsentAlwaysWithSameAuthIDCrossPlatform -->
  <testcase name="DeleteSite" time="12.984" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <skipped/>
  </testcase> <!-- DeleteSite -->
  <testcase name="EditSiteWithNoConsentGivenBefore" time="15.782" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <skipped/>
  </testcase> <!-- EditSiteWithNoConsentGivenBefore -->
  <testcase name="CheckErrorForMandatoryFieldForParameter" time="63.555" classname="com.mobile.tests.GDPR_MetaAppE2ETests"/>
  <testcase name="CheckErrorForWrongCampaignDetails" time="18.779" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <error type="org.testng.TestNGException" message="
Cannot inject @Test annotated Method [CheckErrorForWrongCampaignDetails] with [class java.lang.String].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection">
      <![CDATA[org.testng.TestNGException: 
Cannot inject @Test annotated Method [CheckErrorForWrongCampaignDetails] with [class java.lang.String].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:244)
	at org.testng.internal.Parameters.createParameters(Parameters.java:172)
	at org.testng.internal.Parameters.createParameters(Parameters.java:458)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:569)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- CheckErrorForWrongCampaignDetails -->
  <testcase name="TestDestroy" time="25.135" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <failure type="java.lang.AssertionError" message="Exception occured while killing Mobile driver. Exception details - A session is either terminated or not started
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;Vishals-Mac.local&#039;, ip: &#039;fe80:0:0:0:c20:3d65:1640:1787%en0&#039;, os.name: &#039;Mac OS X&#039;, os.arch: &#039;x86_64&#039;, os.version: &#039;10.14.6&#039;, java.version: &#039;1.8.0_222&#039;
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /Users/vrushalideshpande/Do..., appActivity: com.sourcepointmeta.app.ui...., appPackage: com.sourcepointmeta.app, automationName: uiautomator2, databaseEnabled: false, desired: {app: /Users/vrushalideshpande/Do..., appActivity: com.sourcepointmeta.app.ui...., appPackage: com.sourcepointmeta.app, automationName: uiautomator2, deviceName: emulator-5554, newCommandTimeout: 60, platformName: android, platformVersion: 10, udid: emulator-5554, unicodeKeyboard: false}, deviceApiLevel: 29, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenDensity: 440, deviceScreenSize: 1080x2160, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 60, pixelRatio: 2.75, platform: LINUX, platformName: Android, platformVersion: 10, statBarHeight: 66, takesScreenshot: true, udid: emulator-5554, unicodeKeyboard: false, viewportRect: {height: 1962, left: 0, top: 66, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: f66e2ab4-369c-4343-a00d-862d28fdaa17">
      <![CDATA[java.lang.AssertionError: Exception occured while killing Mobile driver. Exception details - A session is either terminated or not started
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Vishals-Mac.local', ip: 'fe80:0:0:0:c20:3d65:1640:1787%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_222'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /Users/vrushalideshpande/Do..., appActivity: com.sourcepointmeta.app.ui...., appPackage: com.sourcepointmeta.app, automationName: uiautomator2, databaseEnabled: false, desired: {app: /Users/vrushalideshpande/Do..., appActivity: com.sourcepointmeta.app.ui...., appPackage: com.sourcepointmeta.app, automationName: uiautomator2, deviceName: emulator-5554, newCommandTimeout: 60, platformName: android, platformVersion: 10, udid: emulator-5554, unicodeKeyboard: false}, deviceApiLevel: 29, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenDensity: 440, deviceScreenSize: 1080x2160, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 60, pixelRatio: 2.75, platform: LINUX, platformName: Android, platformVersion: 10, statBarHeight: 66, takesScreenshot: true, udid: emulator-5554, unicodeKeyboard: false, viewportRect: {height: 1962, left: 0, top: 66, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: f66e2ab4-369c-4343-a00d-862d28fdaa17
	at org.testng.Assert.fail(Assert.java:93)
	at com.cybage.frameworkutility.utilities.Report.LogFail(Report.java:748)
	at com.cybage.mobileFramework.BaseMobileDriver.quit(BaseMobileDriver.java:443)
	at com.frameworkbase.DriverBase.TestDestroy(DriverBase.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:723)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- TestDestroy -->
  <testcase name="ResetCookies" time="0.000" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <skipped/>
  </testcase> <!-- ResetCookies -->
  <testcase name="CheckErrorForWrongSiteDetails" time="27.653" classname="com.mobile.tests.GDPR_MetaAppE2ETests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [false] but found [true]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.cybage.frameworkutility.assertion.CustomSoftAssert.assertAll(CustomSoftAssert.java:310)
	at com.mobile.tests.GDPR_MetaAppE2ETests.CheckErrorForWrongSiteDetails(GDPR_MetaAppE2ETests.java:1110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- CheckErrorForWrongSiteDetails -->
</testsuite> <!-- com.mobile.tests.GDPR_MetaAppE2ETests -->
